import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Layout from "../components/layout";
import { Typography, Button, Stack, Box, Divider, Paper } from "@mui/material";
import EmailIcon from "@mui/icons-material/Email";
import PhoneIcon from "@mui/icons-material/Phone";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next | CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
          }}
        >
          <Stack spacing={6} display="flex" justifyContent="center">
            <Typography variant="h3" sx={{ textAlign: "center" }}>
              Lets Make Your Personal Card
            </Typography>
            <Link href="/card">
              <Button
                variant="contained"
                size="large"
                sx={{ textTransform: "none", width: "50%" }}
              >
                Get Start
              </Button>
            </Link>
            <Paper
              sx={{
                padding: "0.8rem",
                borderRadius: "1rem",
                boxShadow: "0px 0px 20px 10px #6666668c",
              }}
            >
              <Stack
                direction="row"
                display="flex"
                justifyContent="space-between"
              >
                <Box>
                  <Typography variant="h5">Land Mark Estate</Typography>
                  <Divider />
                  <Typography
                    variant="subtitle2"
                    color="error"
                    sx={{ fontSize: "15px" }}
                  >
                    Real Estate & Builders
                  </Typography>
                </Box>
                <Box>
                  <Typography variant="h5">Tanzeel Hassan Ali</Typography>
                  <Divider />
                  <Typography
                    variant="subtitle2"
                    color="error"
                    sx={{ fontSize: "15px" }}
                  >
                    Cheif Executive Officer
                  </Typography>
                </Box>
              </Stack>
              <Box sx={{ maxWidth: "50%", marginTop: "2rem" }}>
                <Stack
                  direction="row"
                  display="flex"
                  justifyContent="space-between"
                >
                  <Box>
                    <Typography variant="body1" sx={{ fontWeight: "bold" }}>
                      Description:
                    </Typography>
                    <Typography variant="subtitle2">
                      Lorem ipsum dolor sit amet, usu at dicam dolore inimicus.
                      Ad voluptua definiebas vim, te vim omnes postulant.
                      Oblique facilisis id qui.
                    </Typography>
                  </Box>
                  <Typography>Zia</Typography>
                </Stack>
              </Box>
              <Divider />
              <Stack
                direction="row"
                display="flex"
                justifyContent="space-between"
                pt={2}
              >
                <Box>
                  <Stack direction="row">
                    <EmailIcon color="error" />
                    <Typography variant="subtitle2" color="error">
                      ziasarwar20297@gmail.com
                    </Typography>
                  </Stack>
                </Box>
                <Box>
                  <Stack direction="row">
                    <PhoneIcon color="error" />
                    <Typography variant="subtitle2" color="error">
                      03204341299
                    </Typography>
                  </Stack>
                </Box>
              </Stack>
            </Paper>
          </Stack>
        </Box>
      </Layout>
    </>
  );
};

export default Home;
